### ISSUE TITLE
Breaking Note Blocks Plays a Note

### ISSUE THREAD

**Issue by Boobies** [DaCubeKing/ClientSideNoteblocks#2]
When you try to break a block, it will play a note. If you do it in Creative, this will cause it to only play the note and not its breaking sound. If you do it in Survival, you will hear the note when you start breaking and the breaking sound when you are done.

**Comment by DaCubeKing** [comment]
In survival mode the breaking sounds are meant to be suppressed for noteblocks to make the sound cleaner when playing the noteblocks. I'll fix the sounds playing in creative mode though.
